AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda function to save entries in DynamoDB table'

Parameters:
  UserTableName:
    Type: String
    Default: 'User'
    Description: 'Name of the DynamoDB table to store users'

  ProductTableName:
    Type: String
    Default: 'Products'
    Description: 'Name of the DynamoDB table to store products'

  OrderTableName:
    Type: String
    Default: 'Orders'
    Description: 'Name of the DynamoDB table to store products'

Resources:
  UserTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref UserTableName
      AttributeDefinitions:
        - AttributeName: 'user_id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'user_id'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST

  ProductTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref ProductTableName
      AttributeDefinitions:
        - AttributeName: 'product_name'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'product_name'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST

  OrderTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref OrderTableName
      AttributeDefinitions:
        - AttributeName: 'order_id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'order_id'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST

  RegisterUserLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'RegisterUserLambda'
      Runtime: 'python3.9'
      Code:
        S3Bucket: order-products-bucket
        S3Key: 'lambda-code.zip'
      Role: 'arn:aws:iam::121724640456:role/LabRole'
      Handler: register_user.handler
      Timeout: 10

  SendEmailLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'SendEmailLambda'
      Runtime: 'python3.9'
      Code:
        S3Bucket: order-products-bucket
        S3Key: 'lambda-code.zip'
      Role: 'arn:aws:iam::121724640456:role/LabRole'
      Handler: send_email.handler
      Timeout: 10

  UpdateProductsLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'UpdateProductsLambda'
      Runtime: 'python3.9'
      Code:
        S3Bucket: order-products-bucket
        S3Key: 'lambda-code.zip'
      Role: 'arn:aws:iam::121724640456:role/LabRole'
      Handler: update_products.handler
      Timeout: 10

  GetProductsLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'GetProductsLambda'
      Runtime: 'python3.9'
      Code:
        S3Bucket: order-products-bucket
        S3Key: 'lambda-code.zip'
      Role: 'arn:aws:iam::121724640456:role/LabRole'
      Handler: get_products.handler
      Timeout: 10

  PlaceOrderLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'PlaceOrderLambda'
      Runtime: 'python3.9'
      Code:
        S3Bucket: order-products-bucket
        S3Key: 'lambda-code.zip'
      Role: 'arn:aws:iam::121724640456:role/LabRole'
      Handler: place_order.handler
      Timeout: 10

  OrderSNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: 'Orders'
      TopicName: 'Orders'

  UpdateProductsQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: 'UpdateProductsQueue'

  SendEmailQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: 'SendEmailQueue'

  UpdateProductsSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Ref OrderSNSTopic
      Protocol: 'sqs'
      Endpoint: !GetAtt UpdateProductsQueue.Arn

  SendEmailSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Ref OrderSNSTopic
      Protocol: 'sqs'
      Endpoint: !GetAtt SendEmailQueue.Arn

  SendEmailLambdaQueueMapping:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      BatchSize: 1
      EventSourceArn: !GetAtt SendEmailQueue.Arn
      FunctionName: !Ref SendEmailLambda

  UpdateProductsLambdaQueueMapping:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      BatchSize: 1
      EventSourceArn: !GetAtt UpdateProductsQueue.Arn
      FunctionName: !Ref UpdateProductsLambda

  UpdateProductsQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      Queues:
        - !Ref UpdateProductsQueue
      PolicyDocument:
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'sns.amazonaws.com'
            Action: 'sqs:SendMessage'
            Resource: !GetAtt UpdateProductsQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref OrderSNSTopic

  SendEmailQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      Queues:
        - !Ref SendEmailQueue
      PolicyDocument:
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'sns.amazonaws.com'
            Action: 'sqs:SendMessage'
            Resource: !GetAtt SendEmailQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref OrderSNSTopic

  # Rest API
  OrderProductsApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: 'OrderProductsApi'

  RegisterUserApiResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref OrderProductsApi
      ParentId: !GetAtt OrderProductsApi.RootResourceId
      PathPart: 'register-user'

  UpdateProductsApiResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref OrderProductsApi
      ParentId: !GetAtt OrderProductsApi.RootResourceId
      PathPart: 'update-products'

  GetProductsApiResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref OrderProductsApi
      ParentId: !GetAtt OrderProductsApi.RootResourceId
      PathPart: 'get-products'

  PlaceOrderApiResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref OrderProductsApi
      ParentId: !GetAtt OrderProductsApi.RootResourceId
      PathPart: 'place-order'

  RegisterUserApiResourceMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: 'NONE'
      RestApiId: !Ref OrderProductsApi
      ResourceId: !Ref RegisterUserApiResource
      HttpMethod: 'POST'
      AuthorizationType: 'NONE'
      Integration:
        Type: 'AWS_PROXY'
        IntegrationHttpMethod: 'POST'
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RegisterUserLambda.Arn}/invocations'
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              "application/json": "$input.json('$')"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          "application/json": "$input.json('$')"
      RequestParameters:
        method.request.querystring.name: false
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  UpdateProductsApiResourceMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref OrderProductsApi
      ResourceId: !Ref UpdateProductsApiResource
      HttpMethod: 'POST'
      AuthorizationType: 'NONE'
      Integration:
        Type: 'AWS_PROXY'
        IntegrationHttpMethod: 'POST'
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateProductsLambda.Arn}/invocations'
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              "application/json": "$input.json('$')"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          "application/json": "$input.json('$')"
      RequestParameters:
        method.request.querystring.name: false
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  GetProductsApiResourceMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref OrderProductsApi
      ResourceId: !Ref GetProductsApiResource
      HttpMethod: 'GET'
      AuthorizationType: 'NONE'
      Integration:
        Type: 'AWS_PROXY'
        IntegrationHttpMethod: 'POST'
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetProductsLambda.Arn}/invocations'
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              "application/json": "$input.json('$')"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          "application/json": "$input.json('$')"
      RequestParameters:
        method.request.querystring.name: false
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  PlaceOrderApiResourceMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref OrderProductsApi
      ResourceId: !Ref PlaceOrderApiResource
      HttpMethod: 'POST'
      AuthorizationType: 'NONE'
      Integration:
        Type: 'AWS_PROXY'
        IntegrationHttpMethod: 'POST'
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PlaceOrderLambda.Arn}/invocations'
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              "application/json": "$input.json('$')"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          "application/json": "$input.json('$')"
      RequestParameters:
        method.request.querystring.name: false
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  RegisterUserApiDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref OrderProductsApi
    DependsOn:
      - RegisterUserApiResourceMethod
      - UpdateProductsApiResourceMethod
      - GetProductsApiResourceMethod
      - PlaceOrderApiResourceMethod

  OrderProductsApiDeploymentStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      RestApiId: !Ref OrderProductsApi
      DeploymentId: !Ref RegisterUserApiDeployment
      StageName: 'v1'

  # Rest API Gateway Permissions
  RegisterUserApiPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt RegisterUserLambda.Arn
      Action: 'lambda:InvokeFunction'
      Principal: 'apigateway.amazonaws.com'
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${OrderProductsApi}/*/*'

  UpdateProductsApiPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt UpdateProductsLambda.Arn
      Action: 'lambda:InvokeFunction'
      Principal: 'apigateway.amazonaws.com'
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${OrderProductsApi}/*/*'

  GetProductsApiPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt GetProductsLambda.Arn
      Action: 'lambda:InvokeFunction'
      Principal: 'apigateway.amazonaws.com'
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${OrderProductsApi}/*/*'

  PlaceOrderApiPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt PlaceOrderLambda.Arn
      Action: 'lambda:InvokeFunction'
      Principal: 'apigateway.amazonaws.com'
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${OrderProductsApi}/*/*'

  # Enable CORS

  RegisterUserOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref OrderProductsApi
      ResourceId: !Ref RegisterUserApiResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              "method.response.header.Access-Control-Allow-Methods": "'POST, OPTIONS'"
              "method.response.header.Access-Control-Allow-Origin": "'*'"
            ResponseTemplates:
              application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          "application/json": '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
          ResponseModels:
            "application/json": "Empty"

  PlaceOrderOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref OrderProductsApi
      ResourceId: !Ref PlaceOrderApiResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              "method.response.header.Access-Control-Allow-Methods": "'*'"
              "method.response.header.Access-Control-Allow-Origin": "'*'"
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          "application/json": "{\"statusCode\": 200}"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
          ResponseModels:
            "application/json": "Empty"

  GetProductsOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref OrderProductsApi
      ResourceId: !Ref GetProductsApiResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              "method.response.header.Access-Control-Allow-Methods": "'*'"
              "method.response.header.Access-Control-Allow-Origin": "'*'"
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          "application/json": "{\"statusCode\": 200}"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
          ResponseModels:
            "application/json": "Empty"

  UpdateProductsOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref OrderProductsApi
      ResourceId: !Ref UpdateProductsApiResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              "method.response.header.Access-Control-Allow-Methods": "'*'"
              "method.response.header.Access-Control-Allow-Origin": "'*'"
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          "application/json": "{\"statusCode\": 200}"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
          ResponseModels:
            "application/json": "Empty"

  # EC2 for frontend

  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-03f65b8614a860c29'
      InstanceType: 't2.small'
      SecurityGroups:
        - !Ref EC2SecurityGroup
      KeyName: TermAssignment
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash -xe
            sudo apt-get update -y 
            sudo apt install git -y 
            sudo apt-get update 
            sudo apt-get install -y nodejs npm 
            git clone https://gitlab-ci-token:glpat-kPyLs4iJAPak3bpkk42P@git.cs.dal.ca/asagar/ordermanagementui.git  /home/ubuntu/app 
            cd /home/ubuntu/app 
            echo "REACT_APP_URL=${OrderProductsApi}" >> /home/ubuntu/app/.env.local
            npm install >> /home/ubuntu/app/frontent.log 2>&1
            npm start >> /home/ubuntu/app/frontent.log 2>&1

  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Allow all inbound and outbound traffic for TCP and HTTPS'
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'  # Allow all incoming traffic
          IpProtocol: 'tcp'
          FromPort: 22
          ToPort: 22
        - CidrIp: '0.0.0.0/0'  # Allow all incoming traffic
          IpProtocol: 'tcp'
          FromPort: 3000
          ToPort: 3000